image: php:8.3-cli

stages:
  - ci

cache:
  paths:
    - vendor/

all_ci_checks:
  stage: ci
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git unzip libsqlite3-dev
    - docker-php-ext-install pdo_sqlite
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --prefer-dist --no-interaction
    - cp .env.example .env
    - php artisan key:generate
    - touch database/database.sqlite
    - php artisan migrate --graceful
  script:
    - php composer.phar lint:check
    - php composer.phar types:check
    - php composer.phar cve:check
    - php artisan test
